modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/txnimc/sol_valheim/issues"
[[mods]]
modId="sol_valheim"
version="${mod_version}"
displayName="SOL: Valheim"
authors="vice, txnimc"
description="Food variety grants temporary health and regeneration, inspired by Valheim."
[[mixins]]
config="sol_valheim-common.mixins.json"
[[dependencies.sol_valheim]]
modId="neoforge"
type="required"
versionRange="[21.1.249,21.2)"
ordering="NONE"
side="BOTH"
[[dependencies.sol_valheim]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
[[dependencies.sol_valheim]]
modId="cloth_config"
type="required"
versionRange="[15,16)"
ordering="AFTER"
side="BOTH"
